name: contrib-viz
channels:
- conda-forge
dependencies:
- conda-forge::gitpython=2.1.5
- conda-forge::ipykernel=4.6.1
- conda-forge::ipywidgets=7.0.3
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::notebook=5.2.0
- conda-forge::pandas=0.20.3
- conda-forge::plotnine=0.2.1
- conda-forge::python=3.6.3
- conda-forge::pyyaml=3.12
- conda-forge::requests=2.18.4
- conda-forge::r-base=3.4.1
- conda-forge::r-cowplot=0.9.4
- conda-forge::r-dplyr=0.7.8
- conda-forge::r-gdtools=0.1.6
- conda-forge::r-ggplot2=2.2.1
- conda-forge::r-irkernel=0.8.7
- conda-forge::r-lubridate=1.7.4
- conda-forge::r-readr=1.3.1
- conda-forge::r-tidyr=0.8.2
- conda-forge::tornado=4.5.3
